name: Github Package Deploy Workflow
on: workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up settings.xml
        run: |
          echo "${{ github.repository_owner }}"
          echo "<settings><servers><server><id>github</id><username>${{ github.repository_owner }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml
          ls -lrt ~/.m2/settings.xml
      #- name: Maven Deploy
      #  run: mvn clean deploy -Pgithub --batch-mode --settings /home/runner/.m2/settings.xml
