name: Maven Deploy Workflow
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true
      snapshot-version:
        description: 'Next snapshot version'
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up settings.xml
        run: |
          echo "<settings><servers><server><id>${{ secrets.OSSRH_ID }}</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_TOKEN }}</password></server></servers><profiles><profile><id>${{ secrets.OSSRH_ID }}</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.executable>gpg</gpg.executable><gpg.passphrase>${{ secrets.GPG_PASSPHRASE}}</gpg.passphrase></properties></profile></profiles></settings>" > /home/runner/.m2/settings.xml
      
      - name: Code Checkout
        run: |
          git init
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          echo "#### Listing files after clone ####"
          ls -a

      - name: Update Release Version ${{ github.event.inputs.release-version }}
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }} -DgenerateBackupPoms=false -DprocessAllModules=true
          git add .
          git commit -m"Automated version update: ${{ github.event.inputs.release-version }}"
          git push

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Maven Deploy
        run: |
          # Retry 3 times before the steps actually fails
          (echo "===== Maven Deploy Attempt: 1 ====" && mvn clean deploy --batch-mode --settings /home/runner/.m2/settings.xml) || \
          (echo "===== Maven Deploy Attempt: 2 ====" && mvn clean deploy --batch-mode --settings /home/runner/.m2/settings.xml) || \
          (echo "===== Maven Deploy Attempt: 3 ====" && mvn clean deploy --batch-mode --settings /home/runner/.m2/settings.xml) || \
          (echo "==== Maven Deploy Step Failed ====" && exit 1)

      - name: Update Snapshot version ${{ github.event.inputs.snapshot-version }}"
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.snapshot-version }}" -DgenerateBackupPoms=false -DprocessAllModules=
          git add . 
          git commit -m"Automated version update: ${{ github.event.inputs.snapshot-version }}""
          git push