name: Java CI with Maven
on: 
  release:
    types: [published, unpublished, created, edited, deleted, prereleased]
  repository_dispatch:
    types: [test]
jobs:
  test-job:
    runs-on: ubuntu-18.04
    steps:
      - name: Get the version
        id: get_version
        run: |
          #sudo apt-get install jq
          echo "::set-env name=TAG::$(curl -s https://api.github.com/repos/riprasad/gitub-actions-demo/releases/latest| jq --raw-output '.tag_name'| cut -c 2-)"
          echo $TAG
          export TAG
          echo $TAG
          echo "-----"
          echo $TAG
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Display settings.xml
        run: |
          echo "<settings><servers><server><id>ossrh</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_TOKEN }}</password></server></servers><profiles><profile><id>ossrh</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.keyname>${{ secrets.GPG_KEY_ID }}</gpg.keyname><gpg.executable>gpg</gpg.executable><gpg.passphrase>passphrase</gpg.passphrase></properties></profile></profiles></settings>" > /home/runner/.m2/settings.xml
          cat /home/runner/.m2/settings.xml
          echo "---------------------------------------------"
          echo $TAG
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
          maven_goals_phases: clean deploy --batch-mode --settings /home/runner/.m2/settings.xml
          #maven_profiles: gpg
      - name: print settings.xml
        run: cat /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/settings.xml
