name: Java CI with Maven
on:
  pull_request:
    branches: [master]
    #types: [closed]
    #paths:
      #- '.github/project.yml'
jobs:
  test-job:
    runs-on: ubuntu-18.04
    if: ${{github.event.pull_request.merged == true}}
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - uses: radcortez/project-metadata-action@master
        name: retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
      - name: maven release ${{steps.metadata.outputs.current-version}}
        run: |
          java -version

      
