name: Tweet Workflow

on:
  pull_request:
    branches: [master]
    types: [closed]
    paths:
      - '.github/project.yaml'
    
jobs:
  tweet:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@master
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yaml'
      - name: Apicurio Website Code Checkout
        run: |
          mkdir website
          cd website
          git init
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git remote add origin "https://github.com/Apicurio/apicurio.github.io.git"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
      - name: Updating Project Website
        run: |
          cd website
          git init
          git add .
          echo "********** Downloading Latest Release JSON File **********"
          cd _data/studio
          rm latestRelease.json
          touch latestRelease.json && curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest > latestRelease.json
          
          echo "********** Copying Latest Release JSON File **********"
          PUBLISHED_AT=$(cat latestRelease.json | jq '.published_at' | sed 's/"//g')
          cp latestRelease.json releases/$PUBLISHED_AT.json
          
          # setting up env variable to use in next step to force commit the file
          echo "::set-env name=FILENAME::$PUBLISHED_AT"
          
          # setting up env variable to use RELEASE_URL in the tweet
          HTML_URL=$(cat latestRelease.json | jq '.html_url' | sed 's/"//g')
          echo "::set-env name=RELEASE_URL::$HTML_URL"
          
          echo "------------------------"
          git status
          echo "------------------------"
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 6.0.0 
          release_name: 6.0.0
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "${{steps.metadata.outputs.name}} version ${{steps.metadata.outputs.release-version}} is out!  Check out the release notes here: ${{ steps.create_release.outputs.html_url }}"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

